version: '3'
services:
  api:
    container_name: api
    build: .
    volumes:
      - .:/workdir
    ports:
      - 8000:8000

  db:
    container_name: db
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'demo'
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password 
    ports:
      - 33306:3306
  
  httpd:
    container_name: httpd
    image: httpd:alpine
    volumes:
      - ./front:/usr/local/apache2/htdocs
    ports:
      - 8001:80
    
volumes:
  mysql_data: